modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"

[[mods]]
modId="customconsumables"
version="1.0.0"
displayName="Custom Pixelmon Consumables"
logoFile="examplemod.png"
authors="Blissy"
description='''
Adds custom consumable items to Pixelmon that affect Pokémon spawning.

Features include:
- Legendary Lure: 1% chance to spawn a legendary Pokémon when used
- Shiny Charm: 50% chance to spawn a shiny Pokémon when used
- Type Attractor: Forces only Pokémon of a specific type to spawn around you
'''

[[dependencies.customconsumables]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"

[[dependencies.customconsumables]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5]"
ordering="NONE"
side="BOTH"

[[dependencies.customconsumables]]
modId="pixelmon"
mandatory=false
versionRange="[9.1.0,)"
ordering="AFTER"
side="BOTH"