name: GemExtension
version: ${version}
main: com.blissy.gemextension.GemExtensionPlugin
api-version: 1.20
depend: [TokenManager]
description: Extension for TokenManager that adds gem currency
author: Blissy

commands:
  gem:
    description: Gem currency commands
    usage: /gem <balance|send|help>
    aliases: [gems]
  gemadmin:
    description: Admin commands for Gem currency
    usage: /gemadmin <give|take|set|reload>
    aliases: [gemsadmin]

permissions:
  gemextension.*:
    description: Gives access to all GemExtension commands
    children:
      gemextension.use: true
      gemextension.balance: true
      gemextension.balance.others: true
      gemextension.send: true
      gemextension.admin: true

  gemextension.use:
    description: Allows use of basic gem commands
    default: true

  gemextension.balance:
    description: Allows checking own gem balance
    default: true

  gemextension.balance.others:
    description: Allows checking other players' gem balances
    default: op

  gemextension.send:
    description: Allows sending gems to other players
    default: true

  gemextension.admin:
    description: Allows access to admin commands
    default: op
    children:
      gemextension.admin.give: true
      gemextension.admin.take: true
      gemextension.admin.set: true
      gemextension.admin.reload: true